# Generated by Django 2.0.5 on 2018-05-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('number_od_chapters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course', verbose_name='This exam for Course ')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choices', models.CharField(max_length=200)),
                ('answer', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('d', 'Dificult'), ('S', 'Simple')], max_length=1)),
                ('objective', models.CharField(choices=[('R', 'Reminding'), ('u', 'Understanding'), ('c', 'Creativity')], max_length=1)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Chapter', verbose_name="Question's Chapter")),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='Courses.Question', verbose_name='Exam Questions '),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course', verbose_name="chapter's course"),
        ),
    ]
