# Generated by Django 2.0.5 on 2018-05-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number_od_chapters',
            new_name='number_of_chapters',
        ),
    ]
