# Generated by Django 2.0.5 on 2018-05-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20180521_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
