# Generated by Django 2.0.5 on 2018-05-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20180521_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_name',
            new_name='name',
        ),
    ]
