# Generated by Django 2.0.5 on 2018-05-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20180521_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='chapter_id',
            new_name='chapter',
        ),
    ]
